export default {
  profileForms: {
    addInfo: {
      first_name: '',
      last_name: '',
      email: '',
      role: 'Worker',
      pay: {
        type: '',
        amount: null,
      },
    },
    farm: {
      farm_name: '',
      address: '',
      gridPoints: {},
      unit: 'metric',
      currency: 'CAD',
      date: 'MM/DD/YY',
      sandbox: false,
    },
    notification: {
      alert_pest: true,
      alert_weather: true,
      alert_worker_finish: true,
      alert_before_planned_date: true,
      alert_action_after_scouting: true,
    },
    userInfo: {
      first_name: '',
      last_name: '',
      email: '',
      phone_number: '',
      address: '',
      profile_picture: '',
    },
    farmInfo: {
      farm_name: '',
      unit: 'metric',
      currency: 'CAD',
      date: 'MM/DD/YY',
      phone_number: '',
      phone_country: '',
      address: '',
      gridPoints: {},
    },
    editInfo: {
      first_name: '',
      last_name: '',
      email: '',
      role: 'Worker',
      pay: {
        type: 'hourly',
        amount: 0,
      },
    },
    signUpInfo: {
      first_name: '',
      last_name: '',
      email: '',
      password: '',
    },
    forms: {
      $form: {
        initialValue: {
          addInfo: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: {
              type: '',
              amount: null,
            },
          },
          farm: {
            farm_name: '',
            address: '',
            gridPoints: {},
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            sandbox: false,
          },
          notification: {
            alert_pest: true,
            alert_weather: true,
            alert_worker_finish: true,
            alert_before_planned_date: true,
            alert_action_after_scouting: true,
          },
          userInfo: {
            first_name: '',
            last_name: '',
            email: '',
            phone_number: '',
            address: '',
            profile_picture: '',
          },
          farmInfo: {
            farm_name: '',
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            phone_number: '',
            phone_country: '',
            address: '',
            gridPoints: {},
          },
          editInfo: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: {
              type: 'hourly',
              amount: 0,
            },
          },
          signUpInfo: {
            first_name: '',
            last_name: '',
            email: '',
            password: '',
          },
        },
        focus: false,
        pending: false,
        pristine: true,
        submitted: false,
        submitFailed: false,
        retouched: false,
        touched: false,
        valid: true,
        validating: false,
        validated: false,
        validity: {},
        errors: {},
        intents: [],
        model: 'profileForms',
        value: {
          addInfo: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: {
              type: '',
              amount: null,
            },
          },
          farm: {
            farm_name: '',
            address: '',
            gridPoints: {},
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            sandbox: false,
          },
          notification: {
            alert_pest: true,
            alert_weather: true,
            alert_worker_finish: true,
            alert_before_planned_date: true,
            alert_action_after_scouting: true,
          },
          userInfo: {
            first_name: '',
            last_name: '',
            email: '',
            phone_number: '',
            address: '',
            profile_picture: '',
          },
          farmInfo: {
            farm_name: '',
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            phone_number: '',
            phone_country: '',
            address: '',
            gridPoints: {},
          },
          editInfo: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: {
              type: 'hourly',
              amount: 0,
            },
          },
          signUpInfo: {
            first_name: '',
            last_name: '',
            email: '',
            password: '',
          },
        },
      },
      addInfo: {
        $form: {
          initialValue: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: {
              type: '',
              amount: null,
            },
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo',
          value: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: {
              type: '',
              amount: null,
            },
          },
        },
        first_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo.first_name',
          value: '',
        },
        last_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo.last_name',
          value: '',
        },
        email: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo.email',
          value: '',
        },
        role: {
          initialValue: 'Worker',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo.role',
          value: 'Worker',
        },
        pay: {
          $form: {
            initialValue: {
              type: '',
              amount: null,
            },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.addInfo.pay',
            value: {
              type: '',
              amount: null,
            },
          },
          type: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.addInfo.pay.type',
            value: '',
          },
          amount: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.addInfo.pay.amount',
            value: null,
          },
        },
      },
      farm: {
        $form: {
          initialValue: {
            farm_name: '',
            address: '',
            gridPoints: {},
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            sandbox: false,
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm',
          value: {
            farm_name: '',
            address: '',
            gridPoints: {},
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            sandbox: false,
          },
        },
        farm_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.farm_name',
          value: '',
        },
        address: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.address',
          value: '',
        },
        gridPoints: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.farm.gridPoints',
            value: {},
          },
        },
        unit: {
          initialValue: 'metric',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.unit',
          value: 'metric',
        },
        currency: {
          initialValue: 'CAD',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.currency',
          value: 'CAD',
        },
        date: {
          initialValue: 'MM/DD/YY',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.date',
          value: 'MM/DD/YY',
        },
        sandbox: {
          initialValue: false,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.sandbox',
          value: false,
        },
      },
      notification: {
        $form: {
          initialValue: {
            alert_pest: true,
            alert_weather: true,
            alert_worker_finish: true,
            alert_before_planned_date: true,
            alert_action_after_scouting: true,
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification',
          value: {
            alert_pest: true,
            alert_weather: true,
            alert_worker_finish: true,
            alert_before_planned_date: true,
            alert_action_after_scouting: true,
          },
        },
        alert_pest: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_pest',
          value: true,
        },
        alert_weather: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_weather',
          value: true,
        },
        alert_worker_finish: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_worker_finish',
          value: true,
        },
        alert_before_planned_date: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_before_planned_date',
          value: true,
        },
        alert_action_after_scouting: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_action_after_scouting',
          value: true,
        },
      },
      userInfo: {
        $form: {
          initialValue: {
            first_name: '',
            last_name: '',
            email: '',
            phone_number: '',
            address: '',
            profile_picture: '',
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo',
          value: {
            first_name: '',
            last_name: '',
            email: '',
            phone_number: '',
            address: '',
            profile_picture: '',
          },
        },
        first_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.first_name',
          value: '',
        },
        last_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.last_name',
          value: '',
        },
        email: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.email',
          value: '',
        },
        phone_number: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.phone_number',
          value: '',
        },
        address: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.address',
          value: '',
        },
        profile_picture: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.profile_picture',
          value: '',
        },
      },
      farmInfo: {
        $form: {
          initialValue: {
            farm_name: '',
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            phone_number: '',
            phone_country: '',
            address: '',
            gridPoints: {},
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo',
          value: {
            farm_name: '',
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            phone_number: '',
            phone_country: '',
            address: '',
            gridPoints: {},
          },
        },
        farm_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.farm_name',
          value: '',
        },
        unit: {
          initialValue: 'metric',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.unit',
          value: 'metric',
        },
        currency: {
          initialValue: 'CAD',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.currency',
          value: 'CAD',
        },
        date: {
          initialValue: 'MM/DD/YY',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.date',
          value: 'MM/DD/YY',
        },
        phone_number: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.phone_number',
          value: '',
        },
        phone_country: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.phone_country',
          value: '',
        },
        address: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.address',
          value: '',
        },
        gridPoints: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.farmInfo.gridPoints',
            value: {},
          },
        },
      },
      editInfo: {
        $form: {
          initialValue: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: {
              type: 'hourly',
              amount: 0,
            },
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo',
          value: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: {
              type: 'hourly',
              amount: 0,
            },
          },
        },
        first_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo.first_name',
          value: '',
        },
        last_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo.last_name',
          value: '',
        },
        email: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo.email',
          value: '',
        },
        role: {
          initialValue: 'Worker',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo.role',
          value: 'Worker',
        },
        pay: {
          $form: {
            initialValue: {
              type: 'hourly',
              amount: 0,
            },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.editInfo.pay',
            value: {
              type: 'hourly',
              amount: 0,
            },
          },
          type: {
            initialValue: 'hourly',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.editInfo.pay.type',
            value: 'hourly',
          },
          amount: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.editInfo.pay.amount',
            value: 0,
          },
        },
      },
      signUpInfo: {
        $form: {
          initialValue: {
            first_name: '',
            last_name: '',
            email: '',
            password: '',
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo',
          value: {
            first_name: '',
            last_name: '',
            email: '',
            password: '',
          },
        },
        first_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo.first_name',
          value: '',
        },
        last_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo.last_name',
          value: '',
        },
        email: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo.email',
          value: '',
        },
        password: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo.password',
          value: '',
        },
      },
    },
  },
  entitiesReducer: {
    userFarmReducer: {
      farmIdUserIdTuple: [
        {
          farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
          user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
        },
      ],
      byFarmIdUserId: {
        '31881f94-83c6-11ec-9fa9-0242ac130004': {
          '2cc91b7a-83c6-11ec-9fa9-0242ac130004': {
            first_name: 'litefarmdev0+Storybook@gmail.com',
            last_name: '',
            profile_picture: null,
            email: 'litefarmdev0+storybook@gmail.com',
            phone_number: null,
            user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
            gender: 'PREFER_NOT_TO_SAY',
            birth_year: null,
            farm_name: 'litefarmdev0+Storybook@gmail.com',
            address: '49.2652639, -123.1676483',
            grid_points: {
              lat: 49.2652639,
              lng: -123.1676483,
            },
            country_id: 37,
            units: {
              currency: 'CAD',
              measurement: 'metric',
            },
            created_by_user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
            updated_by_user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
            created_at: '2022-02-02T01:19:39.935Z',
            updated_at: '2022-02-02T01:19:39.939Z',
            farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
            deleted: false,
            farm_phone_number: null,
            sandbox_farm: false,
            owner_operated: null,
            default_initial_location_id: null,
            role_id: 1,
            status: 'Active',
            has_consent: true,
            consent_version: '3.0',
            wage: {
              type: 'hourly',
              amount: 0,
            },
            step_one: true,
            step_one_end: '2022-02-02T01:19:39.908Z',
            step_two: true,
            step_two_end: '2022-02-02T01:19:42.589Z',
            step_three: true,
            step_three_end: '2022-02-02T01:19:44.774Z',
            step_four: true,
            step_four_end: '2022-02-02T01:19:47.449Z',
            step_five: true,
            step_five_end: '2022-02-02T01:19:48.374Z',
            country: 'Canada',
            role: 'Owner',
          },
        },
      },
      loading: false,
      error: null,
      loaded: true,
      farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
      user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
    },
    certifierSurveyReducer: {
      ids: ['31881f94-83c6-11ec-9fa9-0242ac130004'],
      entities: {
        '31881f94-83c6-11ec-9fa9-0242ac130004': {
          certification_id: null,
          certifier_id: null,
          farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
          interested: false,
          requested_certification: null,
          requested_certifier: null,
          survey_id: '3606f734-83c6-11ec-a3cb-0242ac130004',
        },
      },
      loading: false,
      error: null,
      loaded: true,
    },
    rolesReducer: {
      roles: [],
      loading: false,
      loaded: false,
    },
    cropReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    cropVarietyReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    weatherReducer: {
      ids: ['31881f94-83c6-11ec-9fa9-0242ac130004'],
      entities: {
        '31881f94-83c6-11ec-9fa9-0242ac130004': {
          farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
          loading: false,
          city: 'Vancouver',
          date: 1643764789,
          humidity: '75%',
          iconName: 'wi-day-cloudy',
          temperature: '4',
          wind: '0.89',
          measurement: 'metric',
          lastActiveDatetime: 1643764789247,
          error: null,
          loaded: true,
        },
      },
    },
    barnReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    ceremonialReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    farmSiteBoundaryReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    fieldReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    gardenReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    greenhouseReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    surfaceWaterReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    naturalAreaReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    residenceReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    bufferZoneReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    watercourseReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    fenceReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    gateReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    waterValveReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    sensorReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    showedSpotlightReducer: {
      loaded: true,
      loading: false,
      map: false,
      draw_area: false,
      draw_line: false,
      drop_point: false,
      adjust_area: false,
      adjust_line: false,
      navigation: true,
      introduce_map: true,
      crop_catalog: false,
      documents: false,
      compliance_docs_and_certification: false,
      transplant: false,
      management_plan_creation: false,
      planting_task: false,
      crop_variety_detail: false,
    },
    managementPlanReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    cropManagementPlanReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    plantingManagementPlanReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    containerMethodReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    bedMethodReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    rowMethodReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    broadcastMethodReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    documentReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    certifierReducer: {
      ids: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      entities: {
        1: {
          certification_id: 1,
          certifier_acronym: 'IOPA',
          certifier_id: 1,
          certifier_name: 'Islands Organic Producers Association',
          country_id: 37,
          certifier_country_id: 1,
          survey_id: '60f615459a6b1c00012ee41e ',
        },
        2: {
          certification_id: 1,
          certifier_acronym: 'KOGS',
          certifier_id: 2,
          certifier_name: 'Kootenay Organic Growers Society',
          country_id: 37,
          certifier_country_id: 2,
          survey_id: null,
        },
        3: {
          certification_id: 1,
          certifier_acronym: 'LEOGA',
          certifier_id: 3,
          certifier_name: 'Living Earth Organic Growers',
          country_id: 37,
          certifier_country_id: 3,
          survey_id: null,
        },
        4: {
          certification_id: 1,
          certifier_acronym: 'BCARA',
          certifier_id: 4,
          certifier_name: 'British Columbia Association for Regenerative Agriculture',
          country_id: 37,
          certifier_country_id: 4,
          survey_id: '60f615459a6b1c00012ee41e ',
        },
        5: {
          certification_id: 1,
          certifier_acronym: 'BDASBC',
          certifier_id: 5,
          certifier_name: 'Bio-Dynamic Agricultural Society of British Columbia',
          country_id: 37,
          certifier_country_id: 5,
          survey_id: null,
        },
        6: {
          certification_id: 1,
          certifier_acronym: 'NOOA',
          certifier_id: 6,
          certifier_name: 'North Okanagan Organic Association',
          country_id: 37,
          certifier_country_id: 6,
          survey_id: '61e7250d8929750001770230',
        },
        7: {
          certification_id: 1,
          certifier_acronym: 'SOOPA',
          certifier_id: 7,
          certifier_name: 'Similkameen Okanagan Organic Producers Association',
          country_id: 37,
          certifier_country_id: 7,
          survey_id: null,
        },
        8: {
          certification_id: 1,
          certifier_acronym: 'PACS',
          certifier_id: 8,
          certifier_name: 'Pacific Agricultural Certification Society',
          country_id: 37,
          certifier_country_id: 8,
          survey_id: null,
        },
        9: {
          certification_id: 1,
          certifier_acronym: 'FVOPA',
          certifier_id: 9,
          certifier_name: 'Fraser Valley Organic Producers',
          country_id: 37,
          certifier_country_id: 9,
          survey_id: null,
        },
      },
      loading: false,
      error: null,
      loaded: true,
    },
    certificationReducer: {
      ids: [1, 2],
      entities: {
        1: {
          certification_id: 1,
          certification_translation_key: 'ORGANIC',
          certification_type: 'Organic',
        },
        2: {
          certification_id: 2,
          certification_translation_key: 'PGS',
          certification_type: 'Participatory Guarantee System',
        },
      },
      loading: false,
      error: null,
      loaded: true,
    },
    taskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    cleaningTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    fieldWorkTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    harvestTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    pestControlTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    soilAmendmentTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    plantTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    transplantTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    taskTypeReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    harvestUseTypeReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    productReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
  },
  persistedStateReducer: {
    userLogReducer: {
      lastActiveDatetime: 1643764780134,
      farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
    },
    chooseFarmFlowReducer: {
      ids: [],
      entities: {},
    },
    mapFilterSettingReducer: {
      ids: [],
      entities: {},
    },
    mapCacheReducer: {
      ids: [],
      entities: {},
    },
    appSettingReducer: {},
  },
  tempStateReducer: {
    homeReducer: {
      loading: false,
    },
    mapLocationReducer: {
      successMessage: null,
      canShowSuccessHeader: false,
      canShowSelection: false,
      locations: [],
      zoomLevel: null,
      position: null,
    },
    hookFormPersistReducer: {
      formData: {},
      persistedPaths: [],
      historyStack: [],
    },
    filterReducer: {
      cropCatalogue: {
        STATUS: {},
        LOCATION: {},
        SUPPLIERS: {},
      },
      documents: {
        TYPE: {},
      },
    },
    snackbarReducer: {
      notifications: [],
    },
    navbarReducer: {
      introducingCertifications: false,
    },
  },
  baseReducer: {},
  insightReducer: {
    cropNutritionData: {
      preview: 0,
      data: [],
    },
    soilOMData: {
      preview: 0,
      data: [],
    },
    labourHappinessData: {
      preview: 0,
      data: [],
    },
    biodiversityData: {
      preview: 0,
      data: [],
    },
    pricesData: {
      preview: 0,
      amountOfFarms: 0,
      data: [],
    },
    waterBalanceData: {
      preview: 0,
      data: [],
    },
    waterBalanceSchedule: {},
    nitrogenBalanceData: {
      preview: 0,
      data: [],
    },
    nitrogenFrequencyData: {},
    pricesDistance: 5,
  },
  financeReducer: {
    forms: {
      addSale: {},
      editSale: {},
      expenseDetail: {},
      date_range: null,
      forms: {
        $form: {
          initialValue: {
            addSale: {},
            editSale: {},
            expenseDetail: {},
            date_range: null,
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'financeReducer.forms',
          value: {
            addSale: {},
            editSale: {},
            expenseDetail: {},
            date_range: null,
          },
        },
        addSale: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'financeReducer.forms.addSale',
            value: {},
          },
        },
        editSale: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'financeReducer.forms.editSale',
            value: {},
          },
        },
        expenseDetail: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'financeReducer.forms.expenseDetail',
            value: {},
          },
        },
        date_range: {
          initialValue: null,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'financeReducer.forms.date_range',
          value: null,
        },
      },
    },
    financeReducer: {
      sales: null,
      cropSales: null,
      shifts: null,
    },
  },
  farmReducer: {
    farm_data_schedule: null,
  },
  _persist: {
    version: -1,
    rehydrated: true,
  },
};
