export default {
  entitiesReducer: {
    userFarmReducer: {
      byFarmIdUserId: {
        '31881f94-83c6-11ec-9fa9-0242ac130004': {
          '2cc91b7a-83c6-11ec-9fa9-0242ac130004': {
            first_name: 'litefarmdev0+Storybook@gmail.com',
            last_name: '',
            profile_picture: null,
            email: 'litefarmdev0+storybook@gmail.com',
            phone_number: null,
            user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
            gender: 'PREFER_NOT_TO_SAY',
            birth_year: null,
            farm_name: 'litefarmdev0+Storybook@gmail.com',
            address: '49.2652639, -123.1676483',
            grid_points: {
              lat: 49.2652639,
              lng: -123.1676483,
            },
            country_id: 37,
            units: {
              currency: 'CAD',
              measurement: 'metric',
            },
            created_by_user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
            updated_by_user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
            created_at: '2022-02-02T01:19:39.935Z',
            updated_at: '2022-02-02T01:19:39.939Z',
            farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
            deleted: false,
            farm_phone_number: null,
            sandbox_farm: false,
            owner_operated: null,
            default_initial_location_id: null,
            role_id: 1,
            status: 'Active',
            has_consent: true,
            consent_version: '3.0',
            wage: {
              type: 'hourly',
              amount: 0,
            },
            step_one: true,
            step_one_end: '2022-02-02T01:19:39.908Z',
            step_two: true,
            step_two_end: '2022-02-02T01:19:42.589Z',
            step_three: true,
            step_three_end: '2022-02-02T01:19:44.774Z',
            step_four: true,
            step_four_end: '2022-02-02T01:19:47.449Z',
            step_five: true,
            step_five_end: '2022-02-02T01:19:48.374Z',
            country: 'Canada',
            role: 'Owner',
          },
        },
      },
      loading: false,
      error: null,
      loaded: true,
      farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
      user_id: '2cc91b7a-83c6-11ec-9fa9-0242ac130004',
    },
    certifierSurveyReducer: {
      ids: ['31881f94-83c6-11ec-9fa9-0242ac130004'],
      entities: {
        '31881f94-83c6-11ec-9fa9-0242ac130004': {
          certification_id: null,
          certifier_id: null,
          farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
          interested: false,
          requested_certification: null,
          requested_certifier: null,
          survey_id: '3606f734-83c6-11ec-a3cb-0242ac130004',
        },
      },
      loading: false,
      error: null,
      loaded: true,
    },
    rolesReducer: {
      roles: [],
      loading: false,
      loaded: false,
    },
    cropReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    cropVarietyReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    weatherReducer: {
      ids: ['31881f94-83c6-11ec-9fa9-0242ac130004'],
      entities: {
        '31881f94-83c6-11ec-9fa9-0242ac130004': {
          farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
          loading: false,
          city: 'Vancouver',
          date: 1643764789,
          humidity: '75%',
          iconName: 'wi-day-cloudy',
          temperature: '4',
          wind: '0.89',
          measurement: 'metric',
          lastActiveDatetime: 1643764789247,
          error: null,
          loaded: true,
        },
      },
    },
    showedSpotlightReducer: {
      loaded: true,
      loading: false,
      map: false,
      draw_area: false,
      draw_line: false,
      drop_point: false,
      adjust_area: false,
      adjust_line: false,
      notification: true,
      navigation: true,
      introduce_map: true,
      crop_catalog: false,
      documents: false,
      compliance_docs_and_certification: false,
      transplant: false,
      management_plan_creation: false,
      planting_task: false,
      crop_variety_detail: false,
    },
    managementPlanReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    cropManagementPlanReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    plantingManagementPlanReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    containerMethodReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    bedMethodReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    rowMethodReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    broadcastMethodReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    documentReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    certifierReducer: {
      ids: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      entities: {
        1: {
          certification_id: 1,
          certifier_acronym: 'IOPA',
          certifier_id: 1,
          certifier_name: 'Islands Organic Producers Association',
          country_id: 37,
          certifier_country_id: 1,
          survey_id: '60f615459a6b1c00012ee41e ',
        },
        2: {
          certification_id: 1,
          certifier_acronym: 'KOGS',
          certifier_id: 2,
          certifier_name: 'Kootenay Organic Growers Society',
          country_id: 37,
          certifier_country_id: 2,
          survey_id: null,
        },
        3: {
          certification_id: 1,
          certifier_acronym: 'LEOGA',
          certifier_id: 3,
          certifier_name: 'Living Earth Organic Growers',
          country_id: 37,
          certifier_country_id: 3,
          survey_id: null,
        },
        4: {
          certification_id: 1,
          certifier_acronym: 'BCARA',
          certifier_id: 4,
          certifier_name: 'British Columbia Association for Regenerative Agriculture',
          country_id: 37,
          certifier_country_id: 4,
          survey_id: '60f615459a6b1c00012ee41e ',
        },
        5: {
          certification_id: 1,
          certifier_acronym: 'BDASBC',
          certifier_id: 5,
          certifier_name: 'Bio-Dynamic Agricultural Society of British Columbia',
          country_id: 37,
          certifier_country_id: 5,
          survey_id: null,
        },
        6: {
          certification_id: 1,
          certifier_acronym: 'NOOA',
          certifier_id: 6,
          certifier_name: 'North Okanagan Organic Association',
          country_id: 37,
          certifier_country_id: 6,
          survey_id: '61e7250d8929750001770230',
        },
        7: {
          certification_id: 1,
          certifier_acronym: 'SOOPA',
          certifier_id: 7,
          certifier_name: 'Similkameen Okanagan Organic Producers Association',
          country_id: 37,
          certifier_country_id: 7,
          survey_id: null,
        },
        8: {
          certification_id: 1,
          certifier_acronym: 'PACS',
          certifier_id: 8,
          certifier_name: 'Pacific Agricultural Certification Society',
          country_id: 37,
          certifier_country_id: 8,
          survey_id: null,
        },
        9: {
          certification_id: 1,
          certifier_acronym: 'FVOPA',
          certifier_id: 9,
          certifier_name: 'Fraser Valley Organic Producers',
          country_id: 37,
          certifier_country_id: 9,
          survey_id: null,
        },
      },
      loading: false,
      error: null,
      loaded: true,
    },
    certificationReducer: {
      ids: [1, 2],
      entities: {
        1: {
          certification_id: 1,
          certification_translation_key: 'THIRD_PARTY_ORGANIC',
          certification_type: 'Third-party Organic',
        },
        2: {
          certification_id: 2,
          certification_translation_key: 'PGS',
          certification_type: 'Participatory Guarantee System',
        },
      },
      loading: false,
      error: null,
      loaded: true,
    },
    taskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    cleaningTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    fieldWorkTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    harvestTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    pestControlTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    soilAmendmentTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    plantTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    transplantTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    taskTypeReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    harvestUseTypeReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    irrigationTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      error: null,
      loaded: false,
    },
    irrigationTaskTypesReducer: {
      irrigationTaskTypes: [
        {
          irrigation_type_id: 1,
          irrigation_type_name: 'CHANNEL',
          farm_id: null,
          default_measuring_type: 'VOLUME',
          created_by_user_id: '1',
          updated_by_user_id: '1',
          created_at: '2000-01-01T00:00:00.000Z',
          updated_at: '2000-01-01T00:00:00.000Z',
          deleted: false,
          irrigation_type_translation_key: 'CHANNEL',
        },
      ],
    },
    productReducer: {
      ids: [],
      entities: {},
      loading: false,
      loaded: false,
    },
    alertReducer: {
      ids: ['8350e6e6-7216-11ed-b431-2792462c3cd9'],
      entities: {
        '8350e6e6-7216-11ed-b431-2792462c3cd9': {
          farm_id: '8350e6e6-7216-11ed-b431-2792462c3cd9',
          loading: false,
          error: null,
          loaded: true,
          count: 0,
        },
      },
    },
    mapAddDrawerReducer: {
      ids: [],
      entities: {},
    },
    animalMovementTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      error: null,
      loaded: false,
    },
    soilSampleTaskReducer: {
      ids: [],
      entities: {},
      loading: false,
      error: null,
      loaded: false,
    },
  },
  persistedStateReducer: {
    userLogReducer: {
      lastActiveDatetime: 1643764780134,
      farm_id: '31881f94-83c6-11ec-9fa9-0242ac130004',
    },
    chooseFarmFlowReducer: {
      ids: [],
      entities: {},
    },
    mapFilterSettingReducer: {
      ids: [],
      entities: {},
    },
    mapCacheReducer: {
      ids: [],
      entities: {},
    },
    appSettingReducer: {},
  },
  tempStateReducer: {
    homeReducer: {
      loading: false,
    },
    mapLocationReducer: {
      successMessage: null,
      canShowSuccessHeader: false,
      canShowSelection: false,
      locations: [],
      zoomLevel: null,
      position: null,
    },
    hookFormPersistReducer: {
      formData: {},
      persistedPaths: [],
      historyStack: [],
    },
    filterReducer: {
      cropCatalogue: {
        STATUS: {},
        LOCATION: {},
        SUPPLIERS: {},
      },
      documents: {
        TYPE: {},
      },
    },
    snackbarReducer: {
      notifications: [],
    },
    navbarReducer: {
      introducingCertifications: false,
    },
    offlineDetectorReducer: {
      isOffline: false,
    },
    offlineReadinessReducer: {
      wentOfflineDuringSetup: false,
      cacheValidation: null,
    },
  },
  baseReducer: {},
  insightReducer: {
    soilOMData: {
      preview: 0,
      data: [],
    },
    labourHappinessData: {
      preview: 0,
      data: [],
    },
    biodiversityData: {
      preview: 0,
      data: [],
    },
    pricesData: {
      preview: 0,
      amountOfFarms: 0,
      data: [],
    },
  },
  financeReducer: {
    financeReducer: {
      sales: null,
      cropSales: null,
    },
  },
  farmReducer: {
    farm_data_schedule: null,
  },
  _persist: {
    version: -1,
    rehydrated: true,
  },
};
