version: "3.7"

services:
  db:
    container_name: litefarm-db
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    container_name: litefarm-web
    build:
      context: ./packages/
      dockerfile: ./webapp/prod.Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=integration

  backend:
    container_name: litefarm-api
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    build:
      context: ./packages/
      dockerfile: ./api/prod.Dockerfile
    ports:
      - "5000:5000"
    environment:
      WAIT_HOSTS: localhost:5432
      NODE_ENV: development
      DEV_DATABASE_HOST: ${DEV_DATABASE_HOST}
      DEV_DATABASE: ${DEV_DATABASE}
      DEV_DATABASE_USER: ${DEV_DATABASE_USER}
      DEV_DATABASE_PASSWORD: ${DEV_DATABASE_PASSWORD}

volumes:
  postgres-data:
    driver: local
