import moment from 'moment';

export default {
  toastr: { toastrs: [], confirm: null },
  profileForms: {
    addInfo: {
      first_name: '',
      last_name: '',
      email: '',
      role: 'Worker',
      pay: { type: '', amount: null },
    },
    farm: {
      farm_name: '',
      address: '',
      gridPoints: {},
      unit: 'metric',
      currency: 'CAD',
      date: 'MM/DD/YY',
      sandbox: false,
    },
    notification: {
      alert_pest: true,
      alert_weather: true,
      alert_worker_finish: true,
      alert_before_planned_date: true,
      alert_action_after_scouting: true,
    },
    userInfo: {
      first_name: '',
      last_name: '',
      email: '',
      phone_number: '',
      address: '',
      profile_picture: '',
    },
    farmInfo: {
      farm_name: '',
      unit: 'metric',
      currency: 'CAD',
      date: 'MM/DD/YY',
      phone_number: '',
      phone_country: '',
      address: '',
      gridPoints: {},
    },
    editInfo: {
      first_name: '',
      last_name: '',
      email: '',
      role: 'Worker',
      pay: { type: 'hourly', amount: 0 },
    },
    signUpInfo: { first_name: '', last_name: '', email: '', password: '' },
    forms: {
      $form: {
        initialValue: {
          addInfo: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: { type: '', amount: null },
          },
          farm: {
            farm_name: '',
            address: '',
            gridPoints: {},
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            sandbox: false,
          },
          notification: {
            alert_pest: true,
            alert_weather: true,
            alert_worker_finish: true,
            alert_before_planned_date: true,
            alert_action_after_scouting: true,
          },
          userInfo: {
            first_name: '',
            last_name: '',
            email: '',
            phone_number: '',
            address: '',
            profile_picture: '',
          },
          farmInfo: {
            farm_name: '',
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            phone_number: '',
            phone_country: '',
            address: '',
            gridPoints: {},
          },
          editInfo: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: { type: 'hourly', amount: 0 },
          },
          signUpInfo: { first_name: '', last_name: '', email: '', password: '' },
        },
        focus: false,
        pending: false,
        pristine: true,
        submitted: false,
        submitFailed: false,
        retouched: false,
        touched: false,
        valid: true,
        validating: false,
        validated: false,
        validity: {},
        errors: {},
        intents: [],
        model: 'profileForms',
        value: {
          addInfo: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: { type: '', amount: null },
          },
          farm: {
            farm_name: '',
            address: '',
            gridPoints: {},
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            sandbox: false,
          },
          notification: {
            alert_pest: true,
            alert_weather: true,
            alert_worker_finish: true,
            alert_before_planned_date: true,
            alert_action_after_scouting: true,
          },
          userInfo: {
            first_name: '',
            last_name: '',
            email: '',
            phone_number: '',
            address: '',
            profile_picture: '',
          },
          farmInfo: {
            farm_name: '',
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            phone_number: '',
            phone_country: '',
            address: '',
            gridPoints: {},
          },
          editInfo: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: { type: 'hourly', amount: 0 },
          },
          signUpInfo: { first_name: '', last_name: '', email: '', password: '' },
        },
      },
      addInfo: {
        $form: {
          initialValue: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: { type: '', amount: null },
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo',
          value: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: { type: '', amount: null },
          },
        },
        first_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo.first_name',
          value: '',
        },
        last_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo.last_name',
          value: '',
        },
        email: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo.email',
          value: '',
        },
        role: {
          initialValue: 'Worker',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.addInfo.role',
          value: 'Worker',
        },
        pay: {
          $form: {
            initialValue: { type: '', amount: null },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.addInfo.pay',
            value: { type: '', amount: null },
          },
          type: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.addInfo.pay.type',
            value: '',
          },
          amount: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.addInfo.pay.amount',
            value: null,
          },
        },
      },
      farm: {
        $form: {
          initialValue: {
            farm_name: '',
            address: '',
            gridPoints: {},
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            sandbox: false,
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm',
          value: {
            farm_name: '',
            address: '',
            gridPoints: {},
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            sandbox: false,
          },
        },
        farm_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.farm_name',
          value: '',
        },
        address: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.address',
          value: '',
        },
        gridPoints: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.farm.gridPoints',
            value: {},
          },
        },
        unit: {
          initialValue: 'metric',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.unit',
          value: 'metric',
        },
        currency: {
          initialValue: 'CAD',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.currency',
          value: 'CAD',
        },
        date: {
          initialValue: 'MM/DD/YY',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.date',
          value: 'MM/DD/YY',
        },
        sandbox: {
          initialValue: false,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farm.sandbox',
          value: false,
        },
      },
      notification: {
        $form: {
          initialValue: {
            alert_pest: true,
            alert_weather: true,
            alert_worker_finish: true,
            alert_before_planned_date: true,
            alert_action_after_scouting: true,
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification',
          value: {
            alert_pest: true,
            alert_weather: true,
            alert_worker_finish: true,
            alert_before_planned_date: true,
            alert_action_after_scouting: true,
          },
        },
        alert_pest: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_pest',
          value: true,
        },
        alert_weather: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_weather',
          value: true,
        },
        alert_worker_finish: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_worker_finish',
          value: true,
        },
        alert_before_planned_date: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_before_planned_date',
          value: true,
        },
        alert_action_after_scouting: {
          initialValue: true,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.notification.alert_action_after_scouting',
          value: true,
        },
      },
      userInfo: {
        $form: {
          initialValue: {
            first_name: '',
            last_name: '',
            email: '',
            phone_number: '',
            address: '',
            profile_picture: '',
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo',
          value: {
            first_name: '',
            last_name: '',
            email: '',
            phone_number: '',
            address: '',
            profile_picture: '',
          },
        },
        first_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.first_name',
          value: '',
        },
        last_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.last_name',
          value: '',
        },
        email: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.email',
          value: '',
        },
        phone_number: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.phone_number',
          value: '',
        },
        address: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.address',
          value: '',
        },
        profile_picture: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.userInfo.profile_picture',
          value: '',
        },
      },
      farmInfo: {
        $form: {
          initialValue: {
            farm_name: '',
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            phone_number: '',
            phone_country: '',
            address: '',
            gridPoints: {},
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo',
          value: {
            farm_name: '',
            unit: 'metric',
            currency: 'CAD',
            date: 'MM/DD/YY',
            phone_number: '',
            phone_country: '',
            address: '',
            gridPoints: {},
          },
        },
        farm_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.farm_name',
          value: '',
        },
        unit: {
          initialValue: 'metric',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.unit',
          value: 'metric',
        },
        currency: {
          initialValue: 'CAD',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.currency',
          value: 'CAD',
        },
        date: {
          initialValue: 'MM/DD/YY',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.date',
          value: 'MM/DD/YY',
        },
        phone_number: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.phone_number',
          value: '',
        },
        phone_country: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.phone_country',
          value: '',
        },
        address: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.farmInfo.address',
          value: '',
        },
        gridPoints: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.farmInfo.gridPoints',
            value: {},
          },
        },
      },
      editInfo: {
        $form: {
          initialValue: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: { type: 'hourly', amount: 0 },
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo',
          value: {
            first_name: '',
            last_name: '',
            email: '',
            role: 'Worker',
            pay: { type: 'hourly', amount: 0 },
          },
        },
        first_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo.first_name',
          value: '',
        },
        last_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo.last_name',
          value: '',
        },
        email: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo.email',
          value: '',
        },
        role: {
          initialValue: 'Worker',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.editInfo.role',
          value: 'Worker',
        },
        pay: {
          $form: {
            initialValue: { type: 'hourly', amount: 0 },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.editInfo.pay',
            value: { type: 'hourly', amount: 0 },
          },
          type: {
            initialValue: 'hourly',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.editInfo.pay.type',
            value: 'hourly',
          },
          amount: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'profileForms.editInfo.pay.amount',
            value: 0,
          },
        },
      },
      signUpInfo: {
        $form: {
          initialValue: { first_name: '', last_name: '', email: '', password: '' },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo',
          value: { first_name: '', last_name: '', email: '', password: '' },
        },
        first_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo.first_name',
          value: '',
        },
        last_name: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo.last_name',
          value: '',
        },
        email: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo.email',
          value: '',
        },
        password: {
          initialValue: '',
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'profileForms.signUpInfo.password',
          value: '',
        },
      },
    },
  },
  entitiesReducer: {
    userFarmReducer: {
      farmIdUserIdTuple: [
        {
          farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
          user_id: 'ebdb01b4-5699-11eb-b6ec-244bfe993436',
        },
      ],
      byFarmIdUserId: {
        'eeb2293a-5699-11eb-9407-244bfe993436': {
          'ebdb01b4-5699-11eb-b6ec-244bfe993436': {
            user_id: 'ebdb01b4-5699-11eb-b6ec-244bfe993436',
            farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
            role_id: 1,
            has_consent: true,
            status: 'Active',
            consent_version: '3.0',
            wage: { type: 'hourly', amount: 0 },
            step_one: true,
            step_one_end: '2021-01-14T18:54:29.993Z',
            step_two: true,
            step_two_end: '2021-01-14T18:54:31.368Z',
            step_three: true,
            step_three_end: '2021-01-14T18:54:33.382Z',
            step_four: true,
            step_four_end: '2021-01-14T18:54:34.970Z',
            step_five: true,
            step_five_end: '2021-01-14T18:54:35.981Z',
            role: 'Owner',
            first_name: 'Kike',
            last_name: '',
            profile_picture: null,
            email: 'omarquez+0113@litefarm.org',
            phone_number: null,
            address: '-34.8962153, -56.1899814',
            notification_setting: {
              alert_pest: true,
              alert_weather: true,
              alert_worker_finish: true,
              alert_before_planned_date: true,
              alert_action_after_scouting: true,
            },
            language_preference: 'en',
            status_id: 1,
            gender: 'PREFER_NOT_TO_SAY',
            birth_year: null,
            farm_name: '241234',
            units: { currency: 'UYU', measurement: 'metric' },
            grid_points: { lat: -34.8962153, lng: -56.1899814 },
            farm_phone_number: null,
          },
        },
      },
      loading: false,
      loaded: true,
      user_id: 'ebdb01b4-5699-11eb-b6ec-244bfe993436',
      error: null,
      farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
    },
    certifierSurveyReducer: { ids: [], entities: {}, loading: false },
    rolesReducer: { roles: [], loading: false },
    fieldReducer: {
      ids: [
        'ea93d9c8-9520-41b4-afb4-9b5caa2227af',
        'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
        'b1b559b0-b07c-45f4-b9c4-f425ea4da309',
      ],
      entities: {
        'ea93d9c8-9520-41b4-afb4-9b5caa2227af': {
          field_id: 'ea93d9c8-9520-41b4-afb4-9b5caa2227af',
          farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
          grid_points: [
            { lat: -34.89750004330298, lng: -56.18738502167357 },
            {
              lat: -34.897148060834915,
              lng: -56.18111938141478,
            },
            { lat: -34.89412094934759, lng: -56.1836084713806 },
          ],
          field_name: '32',
          area: 100840,
          station_id: 3442926,
        },
        'c97a1bc4-41d0-4af3-81d5-745727c1cbb6': {
          field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
          farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
          grid_points: [
            { lat: -34.892853753278175, lng: -56.19219154022826 },
            {
              lat: -34.89739444872093,
              lng: -56.187771259771715,
            },
            { lat: -34.89405055007875, lng: -56.18365138672484 },
          ],
          field_name: '23',
          area: 170186,
          station_id: 3442926,
        },
        'b1b559b0-b07c-45f4-b9c4-f425ea4da309': {
          field_id: 'b1b559b0-b07c-45f4-b9c4-f425ea4da309',
          farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
          grid_points: [
            { lat: -34.90116057155725, lng: -56.19416564606322 },
            {
              lat: -34.90520808112639,
              lng: -56.1960539212097,
            },
            { lat: -34.90556002905254, lng: -56.18532508515013 },
            {
              lat: -34.90193489316672,
              lng: -56.185024677740465,
            },
            { lat: -34.90105498168121, lng: -56.19446605347289 },
            {
              lat: -34.903659492331016,
              lng: -56.198285519110094,
            },
          ],
          field_name: 'Field #2',
          area: 403357,
          station_id: 3442926,
        },
      },
      loading: false,
      loaded: true,
      error: null,
    },
    cropReducer: {
      ids: [31, 32],
      entities: {
        31: {
          crop_id: 31,
          crop_common_name: 'Apricot',
          crop_genus: 'Prunus',
          crop_specie: 'armeniaca     ',
          crop_group: 'Fruit and nuts',
          crop_subgroup: 'Pome fruits and stone fruits',
          max_rooting_depth: 1.5,
          depletion_fraction: 0.5,
          is_avg_depth: false,
          initial_kc: 0.55,
          mid_kc: 0.9,
          end_kc: 0.6518,
          max_height: 3,
          is_avg_kc: false,
          nutrient_notes: null,
          percentrefuse: 7,
          refuse: null,
          protein: 1.4,
          lipid: 0.39,
          energy: 48,
          ca: 13,
          fe: 0.39,
          mg: 10,
          ph: 23,
          k: 259,
          na: 1,
          zn: 0.2,
          cu: 0.078,
          fl: null,
          mn: 0.077,
          se: null,
          vita_rae: 96,
          vite: null,
          vitc: 10,
          thiamin: 0.03,
          riboflavin: 0.04,
          niacin: 0.6,
          pantothenic: null,
          vitb6: 0.054,
          folate: 9,
          vitb12: 0,
          vitk: null,
          is_avg_nutrient: false,
          farm_id: null,
          user_added: false,
          nutrient_credits: null,
          crop_translation_key: 'APRICOT',
        },
        32: {
          crop_id: 32,
          crop_common_name: 'Almond',
          crop_genus: 'Prunus',
          crop_specie: 'dulcis     ',
          crop_group: 'Fruit and nuts',
          crop_subgroup: 'Nuts',
          max_rooting_depth: 1.5,
          depletion_fraction: 0.4,
          is_avg_depth: false,
          initial_kc: 0.4,
          mid_kc: 0.9,
          end_kc: 0.6518,
          max_height: 5,
          is_avg_kc: false,
          nutrient_notes: null,
          percentrefuse: 60,
          refuse: null,
          protein: 21.15,
          lipid: 49.93,
          energy: 579,
          ca: 269,
          fe: 3.71,
          mg: 270,
          ph: 481,
          k: 733,
          na: 1,
          zn: 3.12,
          cu: 1.031,
          fl: null,
          mn: 2.179,
          se: null,
          vita_rae: 0,
          vite: null,
          vitc: 0,
          thiamin: 0.205,
          riboflavin: 1.138,
          niacin: 3.618,
          pantothenic: null,
          vitb6: 0.137,
          folate: 44,
          vitb12: 0,
          vitk: null,
          is_avg_nutrient: false,
          farm_id: null,
          user_added: false,
          nutrient_credits: null,
          crop_translation_key: 'ALMOND',
        },
      },
      loading: false,
      error: null,
    },
    fieldCropReducer: {
      ids: [4, 5, 6],
      entities: {
        4: {
          field_crop_id: 4,
          crop_id: 31,
          field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
          start_date: '2021-01-14T18:54:12.120Z',
          end_date: '2021-02-14T18:54:12.120Z',
          area_used: 3404,
          estimated_production: 17020,
          variety: null,
          estimated_revenue: 68080,
          is_by_bed: false,
          bed_config: null,
        },
        5: {
          field_crop_id: 5,
          crop_id: 32,
          field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
          start_date: '2021-01-14T18:55:32.775Z',
          end_date: '2021-02-14T18:55:32.775Z',
          area_used: 6807,
          estimated_production: 13614,
          variety: null,
          estimated_revenue: 27228,
          is_by_bed: false,
          bed_config: null,
        },
        6: {
          field_crop_id: 6,
          crop_id: 31,
          field_id: 'b1b559b0-b07c-45f4-b9c4-f425ea4da309',
          start_date: '2021-01-19T20:16:47.831Z',
          end_date: '2021-02-19T20:16:47.831Z',
          area_used: 92772,
          estimated_production: 463860,
          variety: null,
          estimated_revenue: 1855440,
          is_by_bed: false,
          bed_config: null,
        },
      },
      loading: false,
      loaded: true,
      error: null,
    },
    shiftStepReducer: {
      worker: {
        user_id: 'ebdb01b4-5699-11eb-b6ec-244bfe993436',
      },
      date: moment(),
      selectedTasks: [
        {
          task_id: 1,
          task_name: 'Bed Preparation',
          farm_id: null,
          task_translation_key: 'BED_PREPARATION',
        },
      ],
    },
  },
  persistedStateReducer: {
    userLogReducer: {
      lastActiveDatetime: 1611317838641,
      farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
    },
  },
  tempStateReducer: { homeReducer: {} },
  baseReducer: {},
  logReducer: {
    forms: {
      fertLog: {
        fert_id: null,
        quantity_kg: 0,
        notes: '',
        moisture_percentage: 0,
        n_percentage: 0,
        nh4_n_ppm: 0,
        p_percentage: 0,
        k_percentage: 0,
        field: null,
      },
      fieldWorkLog: { type: null, notes: '', field: null },
      harvestLog: { notes: '', field: null },
      irrigationLog: {
        activity_kind: 'irrigation',
        type: '',
        notes: '',
        flow_rate: null,
        unit: 'l/min',
        hours: null,
        field: null,
      },
      otherLog: { notes: '', field: null },
      pestControlLog: {
        quantity: 0,
        notes: '',
        custom_pesticide_name: '',
        custom_disease_scientific_name: '',
        custom_disease_common_name: '',
        custom_disease_group: 'Other',
        pesticide_id: null,
        disease_id: 1,
        type: '',
        entry_interval: 0,
        harvest_interval: 0,
        active_ingredients: '',
        concentration: 0,
        field: null,
      },
      scoutingLog: {
        activity_kind: 'scouting',
        type: '',
        notes: '',
        action_needed: false,
        field: null,
      },
      seedLog: {
        space_length: null,
        space_width: null,
        space_unit: null,
        rate: null,
        rate_unit: null,
        field: null,
      },
      soilDataLog: {},
      forms: {
        $form: {
          initialValue: {
            fertLog: {
              fert_id: null,
              quantity_kg: 0,
              notes: '',
              moisture_percentage: 0,
              n_percentage: 0,
              nh4_n_ppm: 0,
              p_percentage: 0,
              k_percentage: 0,
              field: null,
            },
            fieldWorkLog: { type: null, notes: '', field: null },
            harvestLog: { notes: '', field: null },
            irrigationLog: {
              activity_kind: 'irrigation',
              type: '',
              notes: '',
              flow_rate: null,
              unit: 'l/min',
              hours: null,
              field: null,
            },
            otherLog: { notes: '', field: null },
            pestControlLog: {
              quantity: 0,
              notes: '',
              custom_pesticide_name: '',
              custom_disease_scientific_name: '',
              custom_disease_common_name: '',
              custom_disease_group: 'Other',
              pesticide_id: null,
              disease_id: 1,
              type: '',
              entry_interval: 0,
              harvest_interval: 0,
              active_ingredients: '',
              concentration: 0,
              field: null,
            },
            scoutingLog: {
              activity_kind: 'scouting',
              type: '',
              notes: '',
              action_needed: false,
              field: null,
            },
            seedLog: {
              space_length: null,
              space_width: null,
              space_unit: null,
              rate: null,
              rate_unit: null,
              field: null,
            },
            soilDataLog: {},
          },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'logReducer.forms',
          value: {
            fertLog: {
              fert_id: null,
              quantity_kg: 0,
              notes: '',
              moisture_percentage: 0,
              n_percentage: 0,
              nh4_n_ppm: 0,
              p_percentage: 0,
              k_percentage: 0,
              field: null,
            },
            fieldWorkLog: { type: null, notes: '', field: null },
            harvestLog: { notes: '', field: null },
            irrigationLog: {
              activity_kind: 'irrigation',
              type: '',
              notes: '',
              flow_rate: null,
              unit: 'l/min',
              hours: null,
              field: null,
            },
            otherLog: { notes: '', field: null },
            pestControlLog: {
              quantity: 0,
              notes: '',
              custom_pesticide_name: '',
              custom_disease_scientific_name: '',
              custom_disease_common_name: '',
              custom_disease_group: 'Other',
              pesticide_id: null,
              disease_id: 1,
              type: '',
              entry_interval: 0,
              harvest_interval: 0,
              active_ingredients: '',
              concentration: 0,
              field: null,
            },
            scoutingLog: {
              activity_kind: 'scouting',
              type: '',
              notes: '',
              action_needed: false,
              field: null,
            },
            seedLog: {
              space_length: null,
              space_width: null,
              space_unit: null,
              rate: null,
              rate_unit: null,
              field: null,
            },
            soilDataLog: {},
          },
        },
        fertLog: {
          $form: {
            initialValue: {
              fert_id: null,
              quantity_kg: 0,
              notes: '',
              moisture_percentage: 0,
              n_percentage: 0,
              nh4_n_ppm: 0,
              p_percentage: 0,
              k_percentage: 0,
              field: null,
            },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog',
            value: {
              fert_id: null,
              quantity_kg: 0,
              notes: '',
              moisture_percentage: 0,
              n_percentage: 0,
              nh4_n_ppm: 0,
              p_percentage: 0,
              k_percentage: 0,
              field: null,
            },
          },
          fert_id: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.fert_id',
            value: null,
          },
          quantity_kg: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.quantity_kg',
            value: 0,
          },
          notes: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.notes',
            value: '',
          },
          moisture_percentage: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.moisture_percentage',
            value: 0,
          },
          n_percentage: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.n_percentage',
            value: 0,
          },
          nh4_n_ppm: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.nh4_n_ppm',
            value: 0,
          },
          p_percentage: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.p_percentage',
            value: 0,
          },
          k_percentage: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.k_percentage',
            value: 0,
          },
          field: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fertLog.field',
            value: null,
          },
        },
        fieldWorkLog: {
          $form: {
            initialValue: { type: null, notes: '', field: null },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fieldWorkLog',
            value: { type: null, notes: '', field: null },
          },
          type: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fieldWorkLog.type',
            value: null,
          },
          notes: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fieldWorkLog.notes',
            value: '',
          },
          field: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.fieldWorkLog.field',
            value: null,
          },
        },
        harvestLog: {
          $form: {
            initialValue: { notes: '', field: null },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.harvestLog',
            value: { notes: '', field: null },
          },
          notes: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.harvestLog.notes',
            value: '',
          },
          field: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.harvestLog.field',
            value: null,
          },
        },
        irrigationLog: {
          $form: {
            initialValue: {
              activity_kind: 'irrigation',
              type: '',
              notes: '',
              flow_rate: null,
              unit: 'l/min',
              hours: null,
              field: null,
            },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.irrigationLog',
            value: {
              activity_kind: 'irrigation',
              type: '',
              notes: '',
              flow_rate: null,
              unit: 'l/min',
              hours: null,
              field: null,
            },
          },
          activity_kind: {
            initialValue: 'irrigation',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.irrigationLog.activity_kind',
            value: 'irrigation',
          },
          type: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.irrigationLog.type',
            value: '',
          },
          notes: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.irrigationLog.notes',
            value: '',
          },
          flow_rate: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.irrigationLog.flow_rate',
            value: null,
          },
          unit: {
            initialValue: 'l/min',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.irrigationLog.unit',
            value: 'l/min',
          },
          hours: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.irrigationLog.hours',
            value: null,
          },
          field: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.irrigationLog.field',
            value: null,
          },
        },
        otherLog: {
          $form: {
            initialValue: { notes: '', field: null },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.otherLog',
            value: { notes: '', field: null },
          },
          notes: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.otherLog.notes',
            value: '',
          },
          field: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.otherLog.field',
            value: null,
          },
        },
        pestControlLog: {
          $form: {
            initialValue: {
              quantity: 0,
              notes: '',
              custom_pesticide_name: '',
              custom_disease_scientific_name: '',
              custom_disease_common_name: '',
              custom_disease_group: 'Other',
              pesticide_id: null,
              disease_id: 1,
              type: '',
              entry_interval: 0,
              harvest_interval: 0,
              active_ingredients: '',
              concentration: 0,
              field: null,
            },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog',
            value: {
              quantity: 0,
              notes: '',
              custom_pesticide_name: '',
              custom_disease_scientific_name: '',
              custom_disease_common_name: '',
              custom_disease_group: 'Other',
              pesticide_id: null,
              disease_id: 1,
              type: '',
              entry_interval: 0,
              harvest_interval: 0,
              active_ingredients: '',
              concentration: 0,
              field: null,
            },
          },
          quantity: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.quantity',
            value: 0,
          },
          notes: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.notes',
            value: '',
          },
          custom_pesticide_name: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.custom_pesticide_name',
            value: '',
          },
          custom_disease_scientific_name: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.custom_disease_scientific_name',
            value: '',
          },
          custom_disease_common_name: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.custom_disease_common_name',
            value: '',
          },
          custom_disease_group: {
            initialValue: 'Other',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.custom_disease_group',
            value: 'Other',
          },
          pesticide_id: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.pesticide_id',
            value: null,
          },
          disease_id: {
            initialValue: 1,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.disease_id',
            value: 1,
          },
          type: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.type',
            value: '',
          },
          entry_interval: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.entry_interval',
            value: 0,
          },
          harvest_interval: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.harvest_interval',
            value: 0,
          },
          active_ingredients: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.active_ingredients',
            value: '',
          },
          concentration: {
            initialValue: 0,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.concentration',
            value: 0,
          },
          field: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.pestControlLog.field',
            value: null,
          },
        },
        scoutingLog: {
          $form: {
            initialValue: {
              activity_kind: 'scouting',
              type: '',
              notes: '',
              action_needed: false,
              field: null,
            },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.scoutingLog',
            value: {
              activity_kind: 'scouting',
              type: '',
              notes: '',
              action_needed: false,
              field: null,
            },
          },
          activity_kind: {
            initialValue: 'scouting',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.scoutingLog.activity_kind',
            value: 'scouting',
          },
          type: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.scoutingLog.type',
            value: '',
          },
          notes: {
            initialValue: '',
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.scoutingLog.notes',
            value: '',
          },
          action_needed: {
            initialValue: false,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.scoutingLog.action_needed',
            value: false,
          },
          field: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.scoutingLog.field',
            value: null,
          },
        },
        seedLog: {
          $form: {
            initialValue: {
              space_length: null,
              space_width: null,
              space_unit: null,
              rate: null,
              rate_unit: null,
              field: null,
            },
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.seedLog',
            value: {
              space_length: null,
              space_width: null,
              space_unit: null,
              rate: null,
              rate_unit: null,
              field: null,
            },
          },
          space_length: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.seedLog.space_length',
            value: null,
          },
          space_width: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.seedLog.space_width',
            value: null,
          },
          space_unit: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.seedLog.space_unit',
            value: null,
          },
          rate: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.seedLog.rate',
            value: null,
          },
          rate_unit: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.seedLog.rate_unit',
            value: null,
          },
          field: {
            initialValue: null,
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.seedLog.field',
            value: null,
          },
        },
        soilDataLog: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'logReducer.forms.soilDataLog',
            value: {},
          },
        },
      },
    },
    logReducer: { logs: null },
    fertReducer: { fertilizers: null },
    pestControlReducer: { pesticides: null, diseases: null },
  },
  shiftReducer: {
    taskTypes: [
      {
        task_id: 1,
        task_name: 'Bed Preparation',
        farm_id: null,
        task_translation_key: 'BED_PREPARATION',
      },
      { task_id: 2, task_name: 'Delivery', farm_id: null, task_translation_key: 'DELIVERY' },
      {
        task_id: 3,
        task_name: 'Sales',
        farm_id: null,
        task_translation_key: 'SALES',
      },
      {
        task_id: 4,
        task_name: 'Social Event',
        farm_id: null,
        task_translation_key: 'SOCIAL_EVENT',
      },
      { task_id: 5, task_name: 'Seeding', farm_id: null, task_translation_key: 'SEEDING' },
      {
        task_id: 6,
        task_name: 'Fertilizing',
        farm_id: null,
        task_translation_key: 'FERTILIZING',
      },
      { task_id: 7, task_name: 'Scouting', farm_id: null, task_translation_key: 'SCOUTING' },
      {
        task_id: 8,
        task_name: 'Harvesting',
        farm_id: null,
        task_translation_key: 'HARVESTING',
      },
      { task_id: 9, task_name: 'Weeding', farm_id: null, task_translation_key: 'WEEDING' },
      {
        task_id: 10,
        task_name: 'Wash and Pack',
        farm_id: null,
        task_translation_key: 'WASH_AND_PACK',
      },
      {
        task_id: 11,
        task_name: 'Pest Control',
        farm_id: null,
        task_translation_key: 'PEST_CONTROL',
      },
      { task_id: 12, task_name: 'Other', farm_id: null, task_translation_key: 'OTHER' },
      {
        task_id: 13,
        task_name: '43 s',
        farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
        task_translation_key: '43 s',
      },
    ],
    selectedTasks: [
      {
        task_id: 1,
        task_name: 'Bed Preparation',
        farm_id: null,
        task_translation_key: 'BED_PREPARATION',
      },
    ],
    availableDuration: 55,
    startEndObj: {
      start: '2021-01-22T09:59:17-03:00',
      end: '2021-01-22T10:59:17-03:00',
      break: '05',
      shiftUserId: 'ebdb01b4-5699-11eb-b6ec-244bfe993436',
      wage: 0,
      isMulti: false,
    },
    shifts: [
      {
        task_name: 'Delivery',
        task_translation_key: 'DELIVERY',
        task_id: 2,
        shift_id: '0e703a96-569a-11eb-9408-244bfe993436',
        is_field: false,
        field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
        field_crop_id: 4,
        field_name: '23',
        crop_id: 31,
        crop_translation_key: 'APRICOT',
        crop_common_name: 'Apricot',
        variety: null,
        area_used: 3404,
        estimated_production: 17020,
        estimated_revenue: 68080,
        start_date: '2021-01-14T18:54:12.120Z',
        end_date: '2021-02-14T18:54:12.120Z',
        start_time: '2021-01-14T18:55:12.000Z',
        end_time: '2021-01-14T21:55:12.000Z',
        wage_at_moment: 0,
        mood: 'happy',
        break_duration: 20,
        user_id: 'ebdb01b4-5699-11eb-b6ec-244bfe993436',
        farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
        wage: { type: 'hourly', amount: 0 },
        first_name: 'Kike',
        last_name: '',
        duration: 160,
        tasks: [
          {
            task_id: 2,
            duration: 160,
            field_crop_id: 4,
            field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
            is_field: false,
            shift_id: '0e703a96-569a-11eb-9408-244bfe993436',
          },
        ],
      },
      {
        task_name: 'Bed Preparation',
        task_translation_key: 'BED_PREPARATION',
        task_id: 1,
        shift_id: '2b7ed5c0-569a-11eb-9409-244bfe993436',
        is_field: false,
        field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
        field_crop_id: 4,
        field_name: '23',
        crop_id: 31,
        crop_translation_key: 'APRICOT',
        crop_common_name: 'Apricot',
        variety: null,
        area_used: 3404,
        estimated_production: 17020,
        estimated_revenue: 68080,
        start_date: '2021-01-14T18:54:12.120Z',
        end_date: '2021-02-14T18:54:12.120Z',
        start_time: '2021-01-14T18:55:01.000Z',
        end_time: '2021-01-14T20:55:01.000Z',
        wage_at_moment: 0,
        mood: 'very sad',
        break_duration: 20,
        user_id: 'ebdb01b4-5699-11eb-b6ec-244bfe993436',
        farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
        wage: { type: 'hourly', amount: 0 },
        first_name: 'Kike',
        last_name: '',
        duration: 50,
        tasks: [
          {
            task_id: 1,
            duration: 50,
            field_crop_id: 4,
            field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
            is_field: false,
            shift_id: '2b7ed5c0-569a-11eb-9409-244bfe993436',
          },
          {
            task_id: 2,
            duration: 50,
            field_crop_id: 4,
            field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
            is_field: false,
            shift_id: '2b7ed5c0-569a-11eb-9409-244bfe993436',
          },
        ],
      },
      {
        task_name: 'Bed Preparation',
        task_translation_key: 'BED_PREPARATION',
        task_id: 1,
        shift_id: '20768810-569c-11eb-8c59-244bfe993436',
        is_field: false,
        field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
        field_crop_id: 4,
        field_name: '23',
        crop_id: 31,
        crop_translation_key: 'APRICOT',
        crop_common_name: 'Apricot',
        variety: null,
        area_used: 3404,
        estimated_production: 17020,
        estimated_revenue: 68080,
        start_date: '2021-01-14T18:54:12.120Z',
        end_date: '2021-02-14T18:54:12.120Z',
        start_time: '2021-01-14T19:09:00.000Z',
        end_time: '2021-01-14T20:09:00.000Z',
        wage_at_moment: 0,
        mood: 'happy',
        break_duration: 0,
        user_id: 'ebdb01b4-5699-11eb-b6ec-244bfe993436',
        farm_id: 'eeb2293a-5699-11eb-9407-244bfe993436',
        wage: { type: 'hourly', amount: 0 },
        first_name: 'Kike',
        last_name: '',
        duration: 30,
        tasks: [
          {
            task_id: 1,
            duration: 30,
            field_crop_id: 4,
            field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
            is_field: false,
            shift_id: '20768810-569c-11eb-8c59-244bfe993436',
          },
          {
            task_id: 1,
            duration: 30,
            field_crop_id: 5,
            field_id: 'c97a1bc4-41d0-4af3-81d5-745727c1cbb6',
            is_field: false,
            shift_id: '20768810-569c-11eb-8c59-244bfe993436',
          },
        ],
      },
    ],
    selectedShift: {},
  },
  insightReducer: {
    cropNutritionData: { preview: 0, data: [] },
    soilOMData: { preview: 0, data: [] },
    labourHappinessData: { preview: 0, data: [] },
    biodiversityData: { preview: 0, data: [] },
    pricesData: { preview: 0, amountOfFarms: 0, data: [] },
    waterBalanceData: { preview: 0, data: [] },
    waterBalanceSchedule: {},
    nitrogenBalanceData: { preview: 0, data: [] },
    nitrogenFrequencyData: {},
    pricesDistance: 5,
  },
  financeReducer: {
    forms: {
      addSale: {},
      editSale: {},
      expenseDetail: {},
      date_range: null,
      forms: {
        $form: {
          initialValue: { addSale: {}, editSale: {}, expenseDetail: {}, date_range: null },
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'financeReducer.forms',
          value: { addSale: {}, editSale: {}, expenseDetail: {}, date_range: null },
        },
        addSale: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'financeReducer.forms.addSale',
            value: {},
          },
        },
        editSale: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'financeReducer.forms.editSale',
            value: {},
          },
        },
        expenseDetail: {
          $form: {
            initialValue: {},
            focus: false,
            pending: false,
            pristine: true,
            submitted: false,
            submitFailed: false,
            retouched: false,
            touched: false,
            valid: true,
            validating: false,
            validated: false,
            validity: {},
            errors: {},
            intents: [],
            model: 'financeReducer.forms.expenseDetail',
            value: {},
          },
        },
        date_range: {
          initialValue: null,
          focus: false,
          pending: false,
          pristine: true,
          submitted: false,
          submitFailed: false,
          retouched: false,
          touched: false,
          valid: true,
          validating: false,
          validated: false,
          validity: {},
          errors: {},
          intents: [],
          model: 'financeReducer.forms.date_range',
          value: null,
        },
      },
    },
    financeReducer: { sales: null, cropSales: null, shifts: null },
  },
  farmReducer: { farm_data_schedule: null },
};
