#!/bin/bash
#####
# NAME
#   ls - show info about docker objects like containers and images
#
# SYNOPSIS
#   ls [-a]
#
# OPTIONS
#   -a: include volumes and networks
#
# EXAMPLES
#   ls      List containers and images
#   ls -a   List containers, images, volumes and networks
#####

all=false

while [ $# != 0 ]; do
  case "$1" in
  "-a")
    all=true && shift 1;;
  *)
    lfraise_invalid_arg "$1";;
  esac
done

lfsubtitlestyle Containers && lflog_and_run docker ps -a
echo && lfsubtitlestyle Images && lflog_and_run docker images

if $all; then
  echo && lfsubtitlestyle Volumes && lflog_and_run docker volume ls
  echo && lfsubtitlestyle Networks && lflog_and_run docker network ls
fi
