#!/bin/bash
#####
# NAME
#   -v - show verbose log output
#
# DESCRIPTION
#   LITEFARM_VERBOSE=true   Enables lflog message output
#
# EXAMPLES
#   lfcli -v web
#
# SEE ALSO
#   config
#####
export LITEFARM_VERBOSE=true
