exports.up = function (knex) {
  return Promise.all([
    knex('permissions').insert([
      { permission_id: 90, name: 'add:gate', description: 'Create a gate' },
      { permission_id: 91, name: 'add:water_valve', description: 'Create a water valve' },
      { permission_id: 92, name: 'add:buffer_zone', description: 'Create a buffer zone' },
      { permission_id: 93, name: 'add:creek', description: 'Create a creek' },
      { permission_id: 94, name: 'add:fence', description: 'Create a fence' },
      { permission_id: 95, name: 'add:ceremonial_area', description: 'Create a ceremonial area' },
      { permission_id: 96, name: 'add:residence', description: 'Create a residence' },
      { permission_id: 97, name: 'add:ground_water', description: 'Create a ground water area' },
      { permission_id: 98, name: 'add:natural_area', description: 'Create a natural area' },
      { permission_id: 99, name: 'add:greenhouse', description: 'Create a greenhouse' },
      { permission_id: 100, name:'add:barn', description: 'Create a barn' },
      { permission_id: 101, name: 'edit:gate', description: 'Edit a gate' },
      { permission_id: 102, name: 'edit:water_valve', description: 'Edit a water valve' },
      { permission_id: 103, name: 'edit:buffer_zone', description: 'Edit a buffer zone' },
      { permission_id: 104, name: 'edit:creek', description: 'Edit a creek' },
      { permission_id: 105, name: 'edit:fence', description: 'Edit a fence' },
      { permission_id: 106, name: 'edit:ceremonial_area', description: 'Edit a ceremonial area' },
      { permission_id: 107, name: 'edit:residence', description: 'Edit a residence' },
      { permission_id: 108, name: 'edit:ground_water', description: 'Edit a ground water area' },
      { permission_id: 109, name: 'edit:natural_area', description: 'Edit a natural area' },
      { permission_id: 110, name: 'edit:greenhouse', description: 'Edit a greenhouse' },
      { permission_id: 111, name: 'edit:barn', description: 'Edit a barn' },
      { permission_id: 112, name: 'delete:location', description: 'Delete any location' },
    ]),
    knex('rolePermissions').insert([
      { role_id: 1, permission_id: 90 },
      { role_id: 2, permission_id: 90 },
      { role_id: 5, permission_id: 90 },
      { role_id: 1, permission_id: 91 },
      { role_id: 2, permission_id: 91 },
      { role_id: 5, permission_id: 91 },
      { role_id: 1, permission_id: 92 },
      { role_id: 2, permission_id: 92 },
      { role_id: 5, permission_id: 92 },
      { role_id: 1, permission_id: 93 },
      { role_id: 2, permission_id: 93 },
      { role_id: 5, permission_id: 93 },
      { role_id: 1, permission_id: 94 },
      { role_id: 2, permission_id: 94 },
      { role_id: 5, permission_id: 94 },
      { role_id: 1, permission_id: 95 },
      { role_id: 2, permission_id: 95 },
      { role_id: 5, permission_id: 95 },
      { role_id: 1, permission_id: 96 },
      { role_id: 2, permission_id: 96 },
      { role_id: 5, permission_id: 96 },
      { role_id: 1, permission_id: 97 },
      { role_id: 2, permission_id: 97 },
      { role_id: 5, permission_id: 97 },
      { role_id: 1, permission_id: 98 },
      { role_id: 2, permission_id: 98 },
      { role_id: 5, permission_id: 98 },
      { role_id: 1, permission_id: 99 },
      { role_id: 2, permission_id: 99 },
      { role_id: 5, permission_id: 99 },
      { role_id: 1, permission_id: 100 },
      { role_id: 2, permission_id: 100 },
      { role_id: 5, permission_id: 100 },
      { role_id: 1, permission_id: 101 },
      { role_id: 2, permission_id: 101 },
      { role_id: 5, permission_id: 101 },
      { role_id: 1, permission_id: 102 },
      { role_id: 2, permission_id: 102 },
      { role_id: 5, permission_id: 102 },
      { role_id: 1, permission_id: 103 },
      { role_id: 2, permission_id: 103 },
      { role_id: 5, permission_id: 103 },
      { role_id: 1, permission_id: 104 },
      { role_id: 2, permission_id: 104 },
      { role_id: 5, permission_id: 104 },
      { role_id: 1, permission_id: 105 },
      { role_id: 2, permission_id: 105 },
      { role_id: 5, permission_id: 105 },
      { role_id: 1, permission_id: 106 },
      { role_id: 2, permission_id: 106 },
      { role_id: 5, permission_id: 106 },
      { role_id: 1, permission_id: 107 },
      { role_id: 2, permission_id: 107 },
      { role_id: 5, permission_id: 107 },
      { role_id: 1, permission_id: 108 },
      { role_id: 2, permission_id: 108 },
      { role_id: 5, permission_id: 108 },
      { role_id: 1, permission_id: 109 },
      { role_id: 2, permission_id: 109 },
      { role_id: 5, permission_id: 109 },
      { role_id: 1, permission_id: 110 },
      { role_id: 2, permission_id: 110 },
      { role_id: 5, permission_id: 110 },
      { role_id: 1, permission_id: 111 },
      { role_id: 2, permission_id: 111 },
      { role_id: 5, permission_id: 111 },
      { role_id: 1, permission_id: 112 },
      { role_id: 2, permission_id: 112 },
      { role_id: 5, permission_id: 112 },
    ]),
  ]);
};

exports.down = function (knex) {
  const permissions  = [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
    104, 105, 106, 107, 108, 109, 110, 111, 112];
  return Promise.all([
    knex('rolePermissions').whereIn('permission_id', permissions).del(),
    knex('permissions').whereIn('permission_id', permissions).del(),
  ]);
};
