module.exports = {
  FILE_ROW_LIMIT_EXCEEDED: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.FILE_ROW_LIMIT_EXCEEDED',
  MISSING_COLUMNS: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.MISSING_COLUMNS',
  EXTERNAL_ID: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.EXTERNAL_ID',
  SENSOR_NAME: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.SENSOR_NAME',
  SENSOR_LATITUDE: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.SENSOR_LATITUDE',
  SENSOR_LONGITUDE: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.SENSOR_LONGITUDE',
  SENSOR_READING_TYPES: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.SENSOR_READING_TYPES',
  SENSOR_DEPTH: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.SENSOR_DEPTH',
  SENSOR_BRAND: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.SENSOR_BRAND',
  SENSOR_MODEL: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.SENSOR_MODEL',
  SENSOR_HARDWARE_VERSION: 'FARM_MAP.BULK_UPLOAD_SENSORS.VALIDATION.SENSOR_HARDWARE_VERSION',
};
