import React from 'react';
import decorators from '../../config/Decorators';
import { chromaticSmallScreen } from '../../config/chromatic';
import PureTaskDetails from '../../../../components/Task/PureTaskDetails';

export default {
  title: 'Page/AddCleaningTask',
  decorators: decorators,
  component: PureTaskDetails,
};

const Template = (args) => <PureTaskDetails {...args} />;

const managementPlanByLocations = {
  '1f31e024-2e98-44e4-9837-80f52d8ab010': [
    {
      crop_common_name: 'Barley',
      crop_genus: 'Hordeum',
      crop_group: 'Cereals',
      crop_id: 9,
      crop_photo_url:
        'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/barley.webp',
      crop_specie: 'vulgare',
      crop_subgroup: 'Cereals',
      crop_translation_key: 'BARLEY',
      farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
      can_be_cover_crop: true,
      planting_depth: 0.03,
      yield_per_area: 0.3,
      average_seed_weight: 0.00003,
      yield_per_plant: 0.01,
      lifecycle: 'ANNUAL',
      seeding_type: 'SEED',
      needs_transplant: false,
      germination_days: 1,
      transplant_days: null,
      harvest_days: 90,
      termination_days: null,
      planting_method: 'ROW_METHOD',
      plant_spacing: 0.0635,
      seeding_rate: null,
      crop_variety_id: '26db3900-fab9-11eb-a22c-391d1a1e54fa',
      crop_variety_name: '1test',
      supplier: '2',
      compliance_file_url: '',
      organic: true,
      treated: 'NO',
      genetically_engineered: null,
      searched: null,
      crop_variety_photo_url:
        'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/barley.webp',
      management_plan_id: 1166,
      notes: '2',
      name: 'Plan 1',
      start_date: null,
      complete_date: null,
      abandon_date: null,
      complete_notes: null,
      abandon_reason: null,
      already_in_ground: false,
      estimated_revenue: null,
      for_cover: false,
      germination_date: '2021-08-13T07:00:00.000Z',
      harvest_date: '2021-08-14T07:00:00.000Z',
      is_seed: true,
      is_wild: null,
      plant_date: null,
      seed_date: '2021-08-12T07:00:00.000Z',
      termination_date: null,
      transplant_date: null,
      crop_management_plan: {
        already_in_ground: false,
        estimated_revenue: null,
        for_cover: false,
        germination_date: '2021-08-13T07:00:00.000Z',
        harvest_date: '2021-08-14T07:00:00.000Z',
        is_seed: true,
        is_wild: null,
        management_plan_id: 1166,
        needs_transplant: false,
        plant_date: null,
        seed_date: '2021-08-12T07:00:00.000Z',
        termination_date: null,
        transplant_date: null,
      },
      planting_management_plans: {
        final: {
          estimated_seeds: 0.907184,
          estimated_seeds_unit: 'lb',
          estimated_yield: 1.814368,
          estimated_yield_unit: 'lb',
          is_final_planting_management_plan: true,
          is_planting_method_known: null,
          location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
          management_plan_id: 1166,
          notes: '1',
          pin_coordinate: null,
          planting_management_plan_id: '934ef282-50bc-4656-af58-19347498a158',
          planting_method: 'BED_METHOD',
          bed_method: {
            bed_length: 0.101599996749,
            bed_length_unit: 'in',
            bed_spacing: 0.152399995123,
            bed_spacing_unit: 'in',
            bed_width: 0.126999995936,
            bed_width_unit: 'in',
            number_of_beds: 1,
            number_of_rows_in_bed: 2,
            plant_spacing: 0.076199997562,
            plant_spacing_unit: 'in',
            planting_depth: 0.101599996749,
            planting_depth_unit: 'in',
            planting_management_plan_id: '934ef282-50bc-4656-af58-19347498a158',
            specify_beds: '3',
          },
          location: {
            farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
            name: '2',
            notes: null,
            location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
            figure_id: '7fa87148-c480-11eb-bb7c-0242ac120002',
            type: 'field',
            total_area: 50614,
            total_area_unit: 'm2',
            grid_points: [
              {
                lat: 49.280988426928936,
                lng: -123.18064993917848,
              },
              {
                lat: 49.279140668080345,
                lng: -123.1756288439026,
              },
              {
                lat: 49.280876443514906,
                lng: -123.17356890737916,
              },
            ],
            perimeter: null,
            perimeter_unit: 'm',
            station_id: 6173331,
            organic_status: 'Non-Organic',
            transition_date: null,
          },
        },
      },
      crop: {
        crop_common_name: 'Barley',
        crop_genus: 'Hordeum',
        crop_group: 'Cereals',
        crop_id: 9,
        crop_photo_url:
          'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/barley.webp',
        crop_specie: 'vulgare',
        crop_subgroup: 'Cereals',
        crop_translation_key: 'BARLEY',
        farm_id: null,
        can_be_cover_crop: true,
        planting_depth: 0.03,
        yield_per_area: 0.3,
        average_seed_weight: 0.00003,
        yield_per_plant: 0.01,
        lifecycle: 'ANNUAL',
        seeding_type: 'SEED',
        needs_transplant: false,
        germination_days: 1,
        transplant_days: null,
        harvest_days: 90,
        termination_days: null,
        planting_method: 'ROW_METHOD',
        plant_spacing: 0.0635,
        seeding_rate: null,
      },
      crop_variety: {
        crop_variety_id: '26db3900-fab9-11eb-a22c-391d1a1e54fa',
        crop_id: 9,
        farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
        crop_variety_name: '1test',
        supplier: '2',
        lifecycle: 'ANNUAL',
        compliance_file_url: '',
        organic: true,
        treated: 'NO',
        genetically_engineered: null,
        searched: null,
        crop_variety_photo_url:
          'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/barley.webp',
      },
      firstTaskDate: 1628751600000,
      status: 'planned',
    },
    {
      crop_common_name: 'Almond',
      crop_genus: 'Prunus',
      crop_group: 'Fruit and nuts',
      crop_id: 32,
      crop_photo_url:
        'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/almond.webp',
      crop_specie: 'dulcis',
      crop_subgroup: 'Nuts',
      crop_translation_key: 'ALMOND',
      farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
      can_be_cover_crop: false,
      planting_depth: 0.0381,
      yield_per_area: 0.11,
      average_seed_weight: null,
      yield_per_plant: 19.28,
      lifecycle: 'PERENNIAL',
      seeding_type: 'SEEDLING_OR_PLANTING_STOCK',
      needs_transplant: false,
      germination_days: 60,
      transplant_days: null,
      harvest_days: 1095,
      termination_days: null,
      planting_method: 'ROW_METHOD',
      plant_spacing: 0.381,
      seeding_rate: null,
      crop_variety_id: 'fd98b0fe-c7dc-11eb-9f35-0242ac120002',
      crop_variety_name: '1',
      supplier: '2',
      compliance_file_url: '',
      organic: null,
      treated: null,
      genetically_engineered: null,
      searched: null,
      crop_variety_photo_url:
        'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/almond.webp',
      management_plan_id: 1177,
      notes: '',
      name: 'Plan 10',
      start_date: null,
      complete_date: null,
      abandon_date: null,
      complete_notes: null,
      abandon_reason: null,
      already_in_ground: true,
      estimated_revenue: null,
      for_cover: false,
      germination_date: null,
      harvest_date: '2021-08-21T07:00:00.000Z',
      is_seed: null,
      is_wild: false,
      plant_date: null,
      seed_date: null,
      termination_date: null,
      transplant_date: null,
      crop_management_plan: {
        already_in_ground: true,
        estimated_revenue: null,
        for_cover: false,
        germination_date: null,
        harvest_date: '2021-08-21T07:00:00.000Z',
        is_seed: null,
        is_wild: false,
        management_plan_id: 1177,
        needs_transplant: false,
        plant_date: null,
        seed_date: null,
        termination_date: null,
        transplant_date: null,
      },
      planting_management_plans: {
        final: {
          estimated_seeds: null,
          estimated_seeds_unit: 'kg',
          estimated_yield: null,
          estimated_yield_unit: 'lb',
          is_final_planting_management_plan: true,
          is_planting_method_known: false,
          location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
          management_plan_id: 1177,
          notes: null,
          pin_coordinate: null,
          planting_management_plan_id: '63af6dd8-1bfc-43c2-b5be-470180cf6b05',
          planting_method: null,
          location: {
            farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
            name: '2',
            notes: null,
            location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
            figure_id: '7fa87148-c480-11eb-bb7c-0242ac120002',
            type: 'field',
            total_area: 50614,
            total_area_unit: 'm2',
            grid_points: [
              {
                lat: 49.280988426928936,
                lng: -123.18064993917848,
              },
              {
                lat: 49.279140668080345,
                lng: -123.1756288439026,
              },
              {
                lat: 49.280876443514906,
                lng: -123.17356890737916,
              },
            ],
            perimeter: null,
            perimeter_unit: 'm',
            station_id: 6173331,
            organic_status: 'Non-Organic',
            transition_date: null,
          },
        },
      },
      crop: {
        crop_common_name: 'Almond',
        crop_genus: 'Prunus',
        crop_group: 'Fruit and nuts',
        crop_id: 32,
        crop_photo_url:
          'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/almond.webp',
        crop_specie: 'dulcis',
        crop_subgroup: 'Nuts',
        crop_translation_key: 'ALMOND',
        farm_id: null,
        can_be_cover_crop: false,
        planting_depth: 0.0381,
        yield_per_area: 0.11,
        average_seed_weight: null,
        yield_per_plant: 19.28,
        lifecycle: 'PERENNIAL',
        seeding_type: 'SEEDLING_OR_PLANTING_STOCK',
        needs_transplant: true,
        germination_days: 60,
        transplant_days: null,
        harvest_days: 1095,
        termination_days: null,
        planting_method: 'ROW_METHOD',
        plant_spacing: 0.381,
        seeding_rate: null,
      },
      crop_variety: {
        crop_variety_id: 'fd98b0fe-c7dc-11eb-9f35-0242ac120002',
        crop_id: 32,
        farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
        crop_variety_name: '1',
        supplier: '2',
        lifecycle: 'PERENNIAL',
        compliance_file_url: '',
        organic: null,
        treated: null,
        genetically_engineered: null,
        searched: null,
        crop_variety_photo_url:
          'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/almond.webp',
      },
      firstTaskDate: 1628319600000,
      status: 'planned',
    },
  ],
  '61f7cd2c-c09d-43cf-9687-a0502236acfd': [
    {
      crop_common_name: 'Almond',
      crop_genus: 'Prunus',
      crop_group: 'Fruit and nuts',
      crop_id: 32,
      crop_photo_url:
        'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/almond.webp',
      crop_specie: 'dulcis',
      crop_subgroup: 'Nuts',
      crop_translation_key: 'ALMOND',
      farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
      can_be_cover_crop: false,
      planting_depth: 0.0381,
      yield_per_area: 0.11,
      average_seed_weight: null,
      yield_per_plant: 19.28,
      lifecycle: 'PERENNIAL',
      seeding_type: 'SEEDLING_OR_PLANTING_STOCK',
      needs_transplant: true,
      germination_days: 60,
      transplant_days: null,
      harvest_days: 1095,
      termination_days: null,
      planting_method: 'ROW_METHOD',
      plant_spacing: 0.381,
      seeding_rate: null,
      crop_variety_id: 'fd98b0fe-c7dc-11eb-9f35-0242ac120002',
      crop_variety_name: '1',
      supplier: '2',
      compliance_file_url: '',
      organic: null,
      treated: null,
      genetically_engineered: null,
      searched: null,
      crop_variety_photo_url:
        'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/almond.webp',
      management_plan_id: 1179,
      notes: '',
      name: 'Plan 12',
      start_date: null,
      complete_date: null,
      abandon_date: null,
      complete_notes: null,
      abandon_reason: null,
      already_in_ground: false,
      for_cover: false,
      germination_date: '2021-11-02T07:00:00.000Z',
      harvest_date: '2024-09-02T07:00:00.000Z',
      is_seed: false,
      plant_date: '2021-08-28T07:00:00.000Z',
      seed_date: '2021-09-03T07:00:00.000Z',
      transplant_date: '2022-11-21T08:00:00.000Z',
      estimated_revenue: null,
      is_wild: null,
      termination_date: null,
      crop_management_plan: {
        already_in_ground: false,
        for_cover: false,
        germination_date: '2021-11-02T07:00:00.000Z',
        harvest_date: '2024-09-02T07:00:00.000Z',
        is_seed: false,
        management_plan_id: 1179,
        needs_transplant: true,
        plant_date: '2021-08-28T07:00:00.000Z',
        seed_date: '2021-09-03T07:00:00.000Z',
        transplant_date: '2022-11-21T08:00:00.000Z',
        estimated_revenue: null,
        is_wild: null,
        termination_date: null,
      },
      planting_management_plans: {
        final: {
          estimated_seeds: 0,
          estimated_seeds_unit: 'lb',
          estimated_yield: 5.141333168811,
          estimated_yield_unit: 'lb',
          is_final_planting_management_plan: true,
          location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
          management_plan_id: 1179,
          planting_management_plan_id: '19b7fae3-812e-453d-8ccb-39ed98c534eb',
          planting_method: 'ROW_METHOD',
          is_planting_method_known: null,
          notes: null,
          pin_coordinate: null,
          row_method: {
            number_of_rows: 2,
            plant_spacing: 0.381,
            plant_spacing_unit: 'in',
            planting_depth: 0.0381,
            planting_depth_unit: 'in',
            planting_management_plan_id: '19b7fae3-812e-453d-8ccb-39ed98c534eb',
            row_length: 0.050799998374,
            row_length_unit: 'in',
            row_spacing_unit: 'in',
            row_width_unit: 'in',
            same_length: true,
            row_spacing: null,
            row_width: null,
            specify_rows: null,
            total_rows_length: null,
            total_rows_length_unit: 'cm',
          },
          location: {
            farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
            name: '3',
            notes: null,
            location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
            figure_id: '7fa88c46-c480-11eb-bb7c-0242ac120002',
            type: 'field',
            total_area: 37415,
            total_area_unit: 'm2',
            grid_points: [
              {
                lat: 49.28056848781515,
                lng: -123.17292517721559,
              },
              {
                lat: 49.278804704488074,
                lng: -123.17485636770631,
              },
              {
                lat: 49.27804877803772,
                lng: -123.17043608724977,
              },
            ],
            perimeter: null,
            perimeter_unit: 'm',
            station_id: 6173331,
            organic_status: 'Non-Organic',
            transition_date: null,
          },
        },
        initial: {
          estimated_seeds: 0,
          estimated_seeds_unit: 'lb',
          estimated_yield: 115.68,
          estimated_yield_unit: 'lb',
          is_final_planting_management_plan: false,
          location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
          management_plan_id: 1179,
          planting_management_plan_id: '0c7787c3-9361-4eb6-8316-c328446b8cc6',
          planting_method: 'BED_METHOD',
          is_planting_method_known: null,
          notes: null,
          pin_coordinate: null,
          bed_method: {
            bed_length: 0.101599996749,
            bed_length_unit: 'in',
            bed_spacing_unit: 'in',
            bed_width_unit: 'in',
            number_of_beds: 2,
            number_of_rows_in_bed: 3,
            plant_spacing: 0.101599996749,
            plant_spacing_unit: 'in',
            planting_depth_unit: 'in',
            planting_management_plan_id: '0c7787c3-9361-4eb6-8316-c328446b8cc6',
            specify_beds: '2',
            bed_spacing: null,
            bed_width: null,
            planting_depth: null,
          },
          location: {
            farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
            name: '3',
            notes: null,
            location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
            figure_id: '7fa88c46-c480-11eb-bb7c-0242ac120002',
            type: 'field',
            total_area: 37415,
            total_area_unit: 'm2',
            grid_points: [
              {
                lat: 49.28056848781515,
                lng: -123.17292517721559,
              },
              {
                lat: 49.278804704488074,
                lng: -123.17485636770631,
              },
              {
                lat: 49.27804877803772,
                lng: -123.17043608724977,
              },
            ],
            perimeter: null,
            perimeter_unit: 'm',
            station_id: 6173331,
            organic_status: 'Non-Organic',
            transition_date: null,
          },
        },
      },
      crop: {
        crop_common_name: 'Almond',
        crop_genus: 'Prunus',
        crop_group: 'Fruit and nuts',
        crop_id: 32,
        crop_photo_url:
          'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/almond.webp',
        crop_specie: 'dulcis',
        crop_subgroup: 'Nuts',
        crop_translation_key: 'ALMOND',
        farm_id: null,
        can_be_cover_crop: false,
        planting_depth: 0.0381,
        yield_per_area: 0.11,
        average_seed_weight: null,
        yield_per_plant: 19.28,
        lifecycle: 'PERENNIAL',
        seeding_type: 'SEEDLING_OR_PLANTING_STOCK',
        needs_transplant: true,
        germination_days: 60,
        transplant_days: null,
        harvest_days: 1095,
        termination_days: null,
        planting_method: 'ROW_METHOD',
        plant_spacing: 0.381,
        seeding_rate: null,
      },
      crop_variety: {
        crop_variety_id: 'fd98b0fe-c7dc-11eb-9f35-0242ac120002',
        crop_id: 32,
        farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
        crop_variety_name: '1',
        supplier: '2',
        lifecycle: 'PERENNIAL',
        compliance_file_url: '',
        organic: null,
        treated: null,
        genetically_engineered: null,
        searched: null,
        crop_variety_photo_url:
          'https://litefarm.nyc3.cdn.digitaloceanspaces.com/default_crop/v2/almond.webp',
      },
      status: 'planned',
    },
  ],
};

export const CleaningTask = Template.bind({});
CleaningTask.args = {
  handleGoBack: () => console.log('handleGoBack called'),
  onSubmit: () => console.log('onSave called'),
  handleCancel: () => console.log('handleCancel called'),
  onError: () => console.log('onError called'),
  useHookFormPersist: () => {},
  persistedFormData: {
    type: 91,
    due_date: '2021-08-23',
    locations: [
      {
        location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
      },
      {
        location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
      },
    ],
    managementPlans: [
      {
        management_plan_id: 1166,
      },
      {
        management_plan_id: 1177,
      },
      {
        management_plan_id: 1179,
      },
    ],
  },
  selectedTaskType: {
    task_type_id: 91,
    task_name: 'Cleaning',
    task_translation_key: 'CLEANING',
    farm_id: null,
  },
  persistedPaths: [],
  products: [],
  system: 'metric',
  managementPlanByLocations,
};
CleaningTask.parameters = {
  ...chromaticSmallScreen,
};

export const PestControlTask = Template.bind({});
PestControlTask.args = {
  handleGoBack: () => console.log('handleGoBack called'),
  onSubmit: () => console.log('onSave called'),
  handleCancel: () => console.log('handleCancel called'),
  onError: () => console.log('onError called'),
  useHookFormPersist: () => {},
  persistedFormData: {
    type: 11,
    due_date: '2021-08-23',
    locations: [
      {
        location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
      },
      {
        location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
      },
    ],
    managementPlans: [
      {
        management_plan_id: 1166,
      },
      {
        management_plan_id: 1177,
      },
      {
        management_plan_id: 1179,
      },
    ],
  },
  selectedTaskType: {
    task_type_id: 11,
    task_name: 'Pest Control',
    task_translation_key: 'PEST_CONTROL',
    farm_id: null,
  },
  persistedPaths: [],
  products: [],
  system: 'metric',
  managementPlanByLocations,
};
PestControlTask.parameters = {
  ...chromaticSmallScreen,
};

export const FieldWorkTask = Template.bind({});
FieldWorkTask.args = {
  handleGoBack: () => console.log('handleGoBack called'),
  onSubmit: () => console.log('onSave called'),
  handleCancel: () => console.log('handleCancel called'),
  onError: () => console.log('onError called'),
  useHookFormPersist: () => {},
  persistedFormData: {
    type: 9,
    due_date: '2021-08-23',
    locations: [
      {
        location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
      },
      {
        location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
      },
    ],
    managementPlans: [
      {
        management_plan_id: 1166,
      },
      {
        management_plan_id: 1177,
      },
      {
        management_plan_id: 1179,
      },
    ],
  },
  selectedTaskType: {
    task_type_id: 9,
    task_name: 'Field Work',
    task_translation_key: 'FIELD_WORK',
    farm_id: null,
  },
  persistedPaths: [],
  products: [],
  system: 'metric',
  managementPlanByLocations,
};
FieldWorkTask.parameters = {
  ...chromaticSmallScreen,
};

export const SoilAmendmentTask = Template.bind({});
SoilAmendmentTask.args = {
  handleGoBack: () => console.log('handleGoBack called'),
  onSubmit: () => console.log('onSave called'),
  handleCancel: () => console.log('handleCancel called'),
  onError: () => console.log('onError called'),
  useHookFormPersist: () => {},
  persistedFormData: {
    type: 6,
    due_date: '2021-08-23',
    locations: [
      {
        location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
      },
      {
        location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
      },
    ],
    managementPlans: [
      {
        management_plan_id: 1166,
      },
      {
        management_plan_id: 1177,
      },
      {
        management_plan_id: 1179,
      },
    ],
  },
  selectedTaskType: {
    task_type_id: 6,
    task_name: 'Soil Amendment',
    task_translation_key: 'SOIL_AMENDMENT',
    farm_id: null,
  },
  farm: {
    farm_id: '71d84984-88cc-11eb-84e5-0a7facd3678d',
    country_id: null,
    interested: true,
  },
  persistedPaths: [],
  products: [],
  system: 'metric',
  managementPlanByLocations,
};
SoilAmendmentTask.parameters = {
  ...chromaticSmallScreen,
};

export const HarvestTask = Template.bind({});
HarvestTask.args = {
  handleGoBack: () => console.log('handleGoBack called'),
  onSubmit: () => console.log('onSave called'),
  handleCancel: () => console.log('handleCancel called'),
  onError: () => console.log('onError called'),
  useHookFormPersist: () => {},
  persistedFormData: {
    type: 8,
    due_date: '2021-08-23',
    locations: [
      {
        location_id: '1f31e024-2e98-44e4-9837-80f52d8ab010',
      },
      {
        location_id: '61f7cd2c-c09d-43cf-9687-a0502236acfd',
      },
    ],
    managementPlans: [
      {
        management_plan_id: 1166,
      },
      {
        management_plan_id: 1177,
      },
      {
        management_plan_id: 1179,
      },
    ],
    harvest_tasks: [
      {
        harvest_everything: false,
        quantity: 0.907184,
        quantity_unit: {
          label: 'lb',
          value: 'lb',
        },
        id: '1f31e024-2e98-44e4-9837-80f52d8ab010.1166',
      },
      {
        harvest_everything: true,
        quantity_unit: {
          label: 't',
          value: 't',
        },
        id: '1f31e024-2e98-44e4-9837-80f52d8ab010.1177',
      },
      {
        harvest_everything: true,
        quantity: 1.3607759999999998,
        quantity_unit: {
          label: 'lb',
          value: 'lb',
        },
        id: '61f7cd2c-c09d-43cf-9687-a0502236acfd.1179',
      },
    ],
  },
  selectedTaskType: {
    task_type_id: 8,
    task_name: 'Harvesting',
    task_translation_key: 'HARVESTING',
    farm_id: null,
  },
  persistedPaths: [],
  products: [],
  system: 'metric',
  managementPlanByLocations,
};
HarvestTask.parameters = {
  ...chromaticSmallScreen,
};
