#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# For packages/api and packages/webapp
npx lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents

# For root directory, which is not managed by lerna
npx lint-staged