#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# For /api /webapp and /shared
npx lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents

# For root directory, which is not managed by lerna
npx lint-staged