name: "Chromatic"
on:
  workflow_dispatch:
  push:
    branches:
      - integration

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/webapp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 22.21
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: packages/webapp/package.json
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Chromatic
        uses: chromaui/action@98132da0fca2211fb41b3af7b49ce85176007851 # v17.8.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/webapp
