name: Crowdin Download Action

on:
  workflow_dispatch:

jobs:
  download-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          skip_untranslated_strings: true
          export_only_approved: true
          source: packages/webapp/public/locales/en/*.json # Sources pattern
          translation: packages/webapp/public/locales/%two_letters_code%/%original_file_name% # Translations pattern
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New Crowdin pull request with translations"
          pull_request_base_branch_name: ${{ github.head_ref }}
          crowdin_branch_name: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.CROWDIN_TEMP_PERSONAL_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
