name: Docker Compose Workflow

on:   
  pull_request:
    branches:
      - integration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up .env file
        run: |
          echo "DEV_DATABASE_HOST=localhost" >> .env
          echo "DEV_DATABASE=pg-litefarm" >> .env
          echo "DEV_DATABASE_USER=postgres" >> .env
          echo "DEV_DATABASE_PASSWORD=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_DB=pg-litefarm" >> .env

      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.ci.yml

      - name: Build and start containers
        run: docker-compose -f docker-compose.ci.yml up -d

      - name: Wait for containers to start
        run: sleep 30s  # Adjust the sleep duration as needed to allow containers to start
      
      - name: List running containers
        run: docker ps

      - name: View frontend container logs
        run: docker logs litefarm-web

      - name: View backend container logs
        run: docker logs litefarm-api

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Cypress dependencies
        working-directory: packages/webapp
        run: pnpm install --config.auto-install-peers=true --no-frozen-lockfile --force

      - name: Check frontend server availability
        run: |
          # Wait for the frontend server to be accessible
          docker run --network=host --rm appropriate/curl -s --retry-connrefused --retry-seconds 10 --retry-max-time 60 --retry-delay 5s \
            --retry-on HTTP/1.1\ 500\ Internal\ Server\ Error \
            --retry-on HTTP/1.1\ 503\ Service\ Unavailable \
            localhost:80

      - name: Run Cypress tests
        working-directory: packages/webapp
        run: npx cypress run --config baseUrl=localhost:80
