name: Docker Compose Workflow

on:   
  pull_request:
    branches:
      - integration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up .env file
        run: |
          echo "DEV_DATABASE_HOST=litefarm-db" >> .env
          echo "DEV_DATABASE=pg-litefarm" >> .env
          echo "DEV_DATABASE_USER=postgres" >> .env
          echo "DEV_DATABASE_PASSWORD=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_DB=pg-litefarm" >> .env

      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.ci.yml

      - name: Build and start containers
        run: docker-compose -f docker-compose.ci.yml up -d

      - name: List running containers
        run: docker ps
      
      - name: find db container ip address
        id: get_ip
        run: |
          CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' litefarm-web) 
          echo "CONTAINER_IP=$CONTAINER_IP" >> $GITHUB_ENV

      - name: check db container logs
        run: docker logs litefarm-db
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Cypress dependencies
        working-directory: packages/webapp
        run: pnpm install --config.auto-install-peers=true --no-frozen-lockfile --force
      
      - name: inspect api logs
        run: docker logs litefarm-api
        
      - name: List running containers
        run: docker ps

      - name: Run Cypress tests
        working-directory: packages/webapp
        run: npx cypress run --config baseUrl=http://${{ env.CONTAINER_IP }}:80
