name: "Storybook Tests"
on:
  pull_request:
    branches:
      - integration
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/webapp/
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run storybook
        id: storybook
        working-directory: packages/webapp
        run: pnpm run storybook
        outputs:
          time: ${{ steps.wait-for-storybook.outputs.time }}

      - name: Wait for Storybook
        id: wait-for-storybook
        run: |
          until nc -z 127.0.0.1 6006; do sleep 1; done
          echo "Storybook is now running on port 6006."
        timeout-minutes: 5

      - name: Run storybook tests
        working-directory: packages/webapp
        run: cat allowed-storybook-tests.txt | xargs -I {} bash -c 'pnpm test-storybook "$@" --maxWorkers=1' _ {}
        needs: wait-for-storybook
