name: "Storybook Tests"
on:
  pull_request:
    branches:
      - integration
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/webapp/
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Check Port Availability
        run: |
          PORT=6006
          if sudo lsof -t -i :$PORT; then
            echo "Port $PORT is in use."
            exit 1
          else
            echo "Port $PORT is available."
          fi

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "echo 'Starting http-server...' && npx http-server storybook-static --port 6006 --silent" \
          "echo 'Waiting for port 6006...' && npx wait-on tcp:6006 --timeout 30000 && pnpm test-storybook"
