name: "Storybook Tests"
on:
  pull_request:
    branches:
      - integration
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/webapp/
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1

      - name: Install pnpm dependencies
        run: |
          sudo apt-get install -y imagemagick xvfb
          pnpm install

      - name: Run storybook tests
        working-directory: packages/webapp
        run: pnpm test-storybook:ci
