name: "Storybook Tests"
on:
  pull_request:
    branches:
      - integration
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/webapp/
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook
        run: |
          echo 'Starting http-server...'
          npx http-server storybook-static --port 6006 --silent
        background: true

      - name: Wait for Port 6006
        run: npx wait-on tcp:6006 --timeout 60000
